# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: 🧪 Tests

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

env: {FORCE_COLOR: 'true'}

jobs:
  gitleaks:
    name: Check for GitLeaks
    runs-on: ubuntu-latest
    steps:
      - {uses: actions/checkout@v4, with: {fetch-depth: 0}}
      - uses: gacts/gitleaks@v1

  run-this-action:
    name: Run action (${{ matrix.runs-on }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Run this action
        id: act
        uses: ./
        with: {node-version: 19}

      - run: |
          echo 'steps.act.outputs.npm-cache-hit = ${{ steps.act.outputs.npm-cache-hit }}'
          echo 'steps.act.outputs.yarn-cache-hit = ${{ steps.act.outputs.yarn-cache-hit }}'
          echo 'steps.act.outputs.node-version = ${{ steps.act.outputs.node-version }}'
